{
    "openapi": "3.1.0",
    "info": {
        "title": "adminApi",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000/admin"
        }
    ],
    "paths": {
        "/login": {
            "post": {
                "summary": "",
                "operationId": "Login as a admin",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "token": {
                                            "type": "string",
                                            "description": "Bearer token"
                                        }
                                    },
                                    "required": [
                                        "token"
                                    ]
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "token": "abcdefy1413123dsaed1="
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OtherErrorResponse"
                                }
                            }
                        }
                    }
                },
                "description": "Login as a admin",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "email",
                                    "password"
                                ]
                            },
                            "examples": {
                                "example-1": {
                                    "value": {
                                        "email": "john.doe@admin.com",
                                        "password": "!Password#123"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/bugs": {
            "post": {
                "summary": "",
                "operationId": "Save bug",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "default": true
                                        }
                                    },
                                    "required": [
                                        "success"
                                    ]
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "success": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "422": {
                        "$ref": "#/components/responses/ValidationError"
                    }
                },
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "Bug name"
                                    },
                                    "description": {
                                        "type": "string",
                                        "description": "Bug description"
                                    }
                                },
                                "required": [
                                    "name",
                                    "description"
                                ]
                            },
                            "examples": {
                                "example-1": {
                                    "value": {
                                        "name": "Bug name",
                                        "description": "Something went wrong while adding new patient"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/patients": {
            "get": {
                "summary": "",
                "tags": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "pagination": {
                                            "type": "object",
                                            "properties": {
                                                "currentPage": {
                                                    "type": "integer"
                                                },
                                                "totalPages": {
                                                    "type": "integer"
                                                },
                                                "currentRecords": {
                                                    "type": "integer"
                                                },
                                                "totalRecords": {
                                                    "type": "integer"
                                                }
                                            }
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Patient"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "pagination": {
                                                "currentPage": 1,
                                                "totalPages": 2,
                                                "currentRecords": 10,
                                                "totalRecords": 19
                                            },
                                            "data": [
                                                {
                                                    "id": 1,
                                                    "firstName": "Patient",
                                                    "lastName": "Patient",
                                                    "pesel": "003005039981",
                                                    "email": "john.doe@patient.com",
                                                    "address": {
                                                        "id": 1,
                                                        "city": "Biłgoraj",
                                                        "zipCode": "23-400",
                                                        "street": "Jana Pawła II",
                                                        "houseNumber": "20",
                                                        "localNumber": "1A"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                },
                "operationId": "Show patients",
                "description": "Show patients",
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "parameters": [
                    {
                        "schema": {
                            "type": "integer",
                            "default": 1
                        },
                        "in": "query",
                        "name": "page",
                        "description": "page",
                        "required": true
                    }
                ]
            }
        },
        "/patients/{patientId}": {
            "parameters": [
                {
                    "schema": {
                        "type": "string"
                    },
                    "name": "patientId",
                    "in": "path",
                    "required": true
                }
            ],
            "get": {
                "summary": "",
                "tags": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Patient"
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "404": {
                        "description": "Patient Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OtherErrorResponse"
                                }
                            }
                        }
                    }
                },
                "operationId": "Show single patient",
                "description": "Show single patient",
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "parameters": []
            },
            "put": {
                "summary": "",
                "operationId": "Edit patient",
                "responses": {
                    "200": {
                        "description": "Return patient with edited data",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Patient"
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OtherErrorResponse"
                                }
                            }
                        }
                    }
                },
                "description": "Edit patient",
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "firstName": {
                                        "type": "string"
                                    },
                                    "lastName": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "address": {
                                        "type": "object",
                                        "required": [
                                            "city",
                                            "zipCode",
                                            "street",
                                            "houseNumber"
                                        ],
                                        "properties": {
                                            "city": {
                                                "type": "string"
                                            },
                                            "zipCode": {
                                                "type": "string"
                                            },
                                            "street": {
                                                "type": "string"
                                            },
                                            "houseNumber": {
                                                "type": "string"
                                            },
                                            "localNumber": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "required": [
                                    "firstName",
                                    "lastName",
                                    "email",
                                    "address"
                                ]
                            },
                            "examples": {
                                "example-1": {
                                    "value": {
                                        "firstName": "John",
                                        "lastName": "Doe",
                                        "email": "john.doe@patient.com",
                                        "address": {
                                            "city": "Warszawa",
                                            "zipCode": "01-202",
                                            "street": "Jaktorowska",
                                            "houseNumber": "17",
                                            "localNumber": "5A"
                                        }
                                    }
                                }
                            }
                        },
                        "application/xml": {
                            "schema": {
                                "type": "object",
                                "properties": {}
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {}
                            }
                        }
                    },
                    "description": ""
                }
            },
            "delete": {
                "summary": "",
                "operationId": "Delete patient",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OtherErrorResponse"
                                }
                            }
                        }
                    }
                },
                "description": "Delete patient account",
                "security": [
                    {
                        "Authorization": []
                    }
                ]
            }
        },
        "/doctors": {
            "get": {
                "summary": "",
                "tags": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "pagination": {
                                            "type": "object",
                                            "properties": {
                                                "currentPage": {
                                                    "type": "integer"
                                                },
                                                "totalPages": {
                                                    "type": "integer"
                                                },
                                                "currentRecords": {
                                                    "type": "integer"
                                                },
                                                "totalRecords": {
                                                    "type": "integer"
                                                }
                                            }
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Doctor"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "pagination": {
                                                "currentPage": 1,
                                                "totalPages": 2,
                                                "currentRecords": 10,
                                                "totalRecords": 19
                                            },
                                            "data": [
                                                {
                                                    "id": 1,
                                                    "firstName": "Dr John",
                                                    "lastName": "Doe",
                                                    "email": "john.doe@doctor.com"
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                },
                "operationId": "Show doctors",
                "description": "Show doctors",
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "parameters": [
                    {
                        "schema": {
                            "type": "integer",
                            "default": 1
                        },
                        "in": "query",
                        "name": "page",
                        "description": "Page number"
                    }
                ]
            },
            "post": {
                "summary": "",
                "operationId": "Create doctor",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Doctor"
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "422": {
                        "$ref": "#/components/responses/ValidationError"
                    }
                },
                "description": "Create doctor",
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "firstName": {
                                        "type": "string"
                                    },
                                    "secondName": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "example-1": {
                                    "value": {
                                        "firstName": "Dr John",
                                        "secondName": "Doe",
                                        "email": "john.doe@doctor.com",
                                        "password": "!Password#123"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/doctors/{doctorId}": {
            "parameters": [
                {
                    "schema": {
                        "type": "string"
                    },
                    "name": "doctorId",
                    "in": "path",
                    "required": true
                }
            ],
            "get": {
                "summary": "",
                "tags": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Doctor"
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OtherErrorResponse"
                                }
                            }
                        }
                    }
                },
                "operationId": "Get single doctor",
                "description": "Get single doctor",
                "security": [
                    {
                        "Authorization": []
                    }
                ]
            },
            "put": {
                "summary": "",
                "operationId": "Edit doctor",
                "responses": {
                    "200": {
                        "description": "Return doctor with updated data",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Doctor"
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OtherErrorResponse"
                                }
                            }
                        }
                    }
                },
                "description": "Edit doctor",
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "firstName": {
                                        "type": "string"
                                    },
                                    "lastName": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "example-1": {
                                    "value": {
                                        "firstName": "Dr John",
                                        "lastName": "Doe",
                                        "email": "john.doe@doctor.com"
                                    }
                                }
                            }
                        },
                        "application/xml": {
                            "schema": {
                                "type": "object",
                                "properties": {}
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {}
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "",
                "operationId": "Delete doctor",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "default": true
                                        }
                                    },
                                    "required": [
                                        "success"
                                    ]
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OtherErrorResponse"
                                }
                            }
                        }
                    }
                },
                "description": "Delete doctor",
                "security": [
                    {
                        "Authorization": []
                    }
                ]
            }
        },
        "/vaccinations": {
            "get": {
                "summary": "",
                "tags": [],
                "responses": {
                    "200": {
                        "description": "Array of vaccinations (sorted by id vaccinationSlot date DESC)",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "pagination": {
                                            "type": "object",
                                            "properties": {
                                                "currentPage": {
                                                    "type": "integer"
                                                },
                                                "totalPages": {
                                                    "type": "integer"
                                                },
                                                "currentRecords": {
                                                    "type": "integer"
                                                },
                                                "totalRecords": {
                                                    "type": "integer"
                                                }
                                            }
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/Vaccination"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "example-1": {
                                        "value": {
                                            "pagination": {
                                                "currentPage": 1,
                                                "totalPages": 2,
                                                "currentRecords": 10,
                                                "totalRecords": 19
                                            },
                                            "data": [
                                                {
                                                    "id": 1,
                                                    "vaccine": {
                                                        "id": 1,
                                                        "name": "Phizer",
                                                        "disease": "COVID-19",
                                                        "requiredDoses": 2,
                                                        "serialNumber": "000-1311231"
                                                    },
                                                    "vaccinationSlot": {
                                                        "id": 1,
                                                        "date": "2019-08-24T14:15:22Z"
                                                    },
                                                    "status": "Planned",
                                                    "patient": {
                                                        "id": 1,
                                                        "firstName": "Patient",
                                                        "lastName": "Patient",
                                                        "pesel": "003005039981",
                                                        "email": "john.doe@patient.com",
                                                        "address": {
                                                            "id": 1,
                                                            "city": "Biłgoraj",
                                                            "zipCode": "23-400",
                                                            "street": "Jana Pawła II",
                                                            "houseNumber": "20",
                                                            "localNumber": "1A"
                                                        }
                                                    },
                                                    "doctor": {
                                                        "id": 1,
                                                        "firstName": "Dr John",
                                                        "lastName": "Doe",
                                                        "email": "john.doe@doctor.com"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "422": {
                        "$ref": "#/components/responses/ValidationError"
                    }
                },
                "operationId": "Get list of vaccinations",
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "Return list of vaccinations",
                "parameters": [
                    {
                        "schema": {
                            "type": "number",
                            "default": 1
                        },
                        "in": "query",
                        "name": "page",
                        "description": "Page number",
                        "allowEmptyValue": true
                    },
                    {
                        "schema": {
                            "type": "number"
                        },
                        "in": "query",
                        "name": "patientId",
                        "description": "Filter by patient id"
                    },
                    {
                        "schema": {
                            "type": "number"
                        },
                        "in": "query",
                        "name": "doctorId",
                        "description": "Filter by doctor id"
                    },
                    {
                        "schema": {
                            "type": "string",
                            "enum": [
                                "COVID-19",
                                "COVID-21",
                                "Flu",
                                "OTHER"
                            ]
                        },
                        "in": "query",
                        "name": "disease",
                        "description": "Filter by disease"
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "Address": {
                "title": "Address",
                "type": "object",
                "examples": [
                    {
                        "id": 0,
                        "city": "Biłgoraj",
                        "zipCode": "23-400",
                        "street": "Jana Pawła II",
                        "houseNumber": "20",
                        "localNumber": "1A"
                    }
                ],
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "city": {
                        "type": "string"
                    },
                    "zipCode": {
                        "type": "string"
                    },
                    "street": {
                        "type": "string"
                    },
                    "houseNumber": {
                        "type": "string"
                    },
                    "localNumber": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "city",
                    "zipCode",
                    "street",
                    "houseNumber"
                ]
            },
            "Doctor": {
                "title": "Doctor",
                "type": "object",
                "examples": [
                    {
                        "id": 1,
                        "firstName": "Dr John",
                        "lastName": "Doe",
                        "email": "john.doe@doctor.com"
                    }
                ],
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "firstName",
                    "lastName",
                    "email"
                ]
            },
            "OtherErrorResponse": {
                "title": "OtherErrorResponse",
                "type": "object",
                "properties": {
                    "success": {
                        "type": "boolean",
                        "default": false,
                        "description": "Is set to false\n"
                    },
                    "msg": {
                        "type": "string",
                        "description": "Error message"
                    }
                },
                "required": [
                    "success",
                    "msg"
                ],
                "examples": [
                    {
                        "success": false,
                        "msg": "String containing error message"
                    }
                ]
            },
            "Patient": {
                "title": "Patient",
                "type": "object",
                "examples": [
                    {
                        "id": 1,
                        "firstName": "Patient",
                        "lastName": "Patient",
                        "pesel": "003005039981",
                        "email": "john.doe@patient.com",
                        "address": {
                            "id": 1,
                            "city": "Biłgoraj",
                            "zipCode": "23-400",
                            "street": "Jana Pawła II",
                            "houseNumber": "20",
                            "localNumber": "1A"
                        }
                    }
                ],
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "pesel": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "address": {
                        "$ref": "#/components/schemas/Address"
                    }
                },
                "required": [
                    "id",
                    "firstName",
                    "lastName",
                    "pesel",
                    "email",
                    "address"
                ]
            },
            "Vaccination": {
                "title": "Vaccination",
                "type": "object",
                "examples": [
                    {
                        "id": 1,
                        "vaccine": {
                            "id": 1,
                            "name": "Phizer",
                            "disease": "COVID-19",
                            "requiredDoses": 2,
                            "serialNumber": "000-1311231"
                        },
                        "vaccinationSlot": {
                            "id": 1,
                            "date": "2019-08-24T14:15:22Z"
                        },
                        "status": "Planned",
                        "patient": {
                            "id": 1,
                            "firstName": "Patient",
                            "lastName": "Patient",
                            "pesel": "003005039981",
                            "email": "john.doe@patient.com",
                            "address": {
                                "id": 1,
                                "city": "Biłgoraj",
                                "zipCode": "23-400",
                                "street": "Jana Pawła II",
                                "houseNumber": "20",
                                "localNumber": "1A"
                            }
                        },
                        "doctor": {
                            "id": 1,
                            "firstName": "Dr John",
                            "lastName": "Doe",
                            "email": "john.doe@doctor.com"
                        }
                    }
                ],
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "vaccine": {
                        "$ref": "#/components/schemas/Vaccine"
                    },
                    "vaccinationSlot": {
                        "$ref": "#/components/schemas/VaccinationSlot"
                    },
                    "status": {
                        "type": "string",
                        "enum": [
                            "Planned",
                            "Completed",
                            "Canceled"
                        ]
                    },
                    "patient": {
                        "$ref": "#/components/schemas/Patient"
                    },
                    "doctor": {
                        "$ref": "#/components/schemas/Doctor"
                    }
                },
                "required": [
                    "id"
                ]
            },
            "VaccinationSlot": {
                "title": "VaccinationSlot",
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "date": {
                        "type": "string",
                        "format": "date-time"
                    }
                },
                "required": [
                    "id",
                    "date"
                ],
                "description": "",
                "examples": [
                    {
                        "id": 1,
                        "date": "2019-08-24T14:15:22Z"
                    }
                ]
            },
            "Vaccine": {
                "title": "Vaccine",
                "type": "object",
                "examples": [
                    {
                        "id": 1,
                        "name": "Phizer",
                        "disease": "COVID-19",
                        "requiredDoses": 2,
                        "serialNumber": "00-10012414881"
                    }
                ],
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "disease": {
                        "type": "string",
                        "enum": [
                            "COVID-19",
                            "COVID-21",
                            "Flu",
                            "OTHER"
                        ]
                    },
                    "requiredDoses": {
                        "type": "integer"
                    },
                    "serialNumber": {
                        "type": [
                            "integer",
                            "string"
                        ]
                    }
                },
                "required": [
                    "id",
                    "name",
                    "disease",
                    "requiredDoses"
                ]
            }
        },
        "securitySchemes": {
            "Authorization": {
                "name": "Authorization",
                "type": "apiKey",
                "in": "header"
            }
        },
        "responses": {
            "Unauthorized": {
                "description": "Unauthorized error (invalid or empry Bearer token)",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "Is set to false",
                                    "default": false
                                },
                                "msg": {
                                    "type": "string",
                                    "default": "Unauthorized"
                                }
                            },
                            "required": [
                                "success",
                                "msg"
                            ]
                        }
                    }
                }
            },
            "ValidationError": {
                "description": "Validation error",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "default": false,
                                    "description": "Is set to false"
                                },
                                "data": {
                                    "type": "object",
                                    "description": "Object of invalid fields"
                                }
                            },
                            "required": [
                                "success",
                                "data"
                            ]
                        },
                        "examples": {
                            "example-1": {
                                "value": {
                                    "success": false,
                                    "data": {
                                        "field1": "Field field1 is required",
                                        "field2": "Field field2 must have at least 5 characters"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}